apiVersion: v1
kind: Pod
metadata:
  name: cpu-spike-pod
  labels:
    app: cpu-spike
spec:
  containers:
  - name: stress-ng
    image: alexeiled/stress-ng
    args: ["--cpu", "1", "--cpu-load", "90", "--timeout", "600s"]
    resources:
      requests:
        cpu: "100m"
      limits:
        cpu: "500m"
