apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stress-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: pvc-stress-pod
  labels:
    app: pvc-stress
spec:
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: stress-pvc
  containers:
  - name: stress-ng
    image: alexeiled/stress-ng
    args: ["--hdd", "1", "--hdd-bytes", "512M", "--timeout", "600s"]
    volumeMounts:
    - name: data
      mountPath: /data
    resources:
      requests:
        cpu: "100m"
      limits:
        cpu: "200m"
